spring:
  application:
    name: bookingapp
  datasource:
    url: jdbc:postgresql://localhost:5440/bookingapp_ai?currentSchema=public
    driver-class-name: org.postgresql.Driver
    username: admin
    password: Passw0rd

  hikari:
    maximum-pool-size: 10
    minimum-idle: 1
    idle-timeout: 30000
    pool-name: bookingAppPoolConnection
    max-lifetime: 200000
    connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false

  sql:
    init:
      mode: always
server:
  port: 8082
