-- Lista negra de clientes por tenant: la presencia de la fila indica que el cliente esta bloqueado
-- para reservar. Se quita borrando la fila (no hay expiracion por tiempo).
create table customer_blacklist (
    customer_blacklist_id bigint generated by default as identity primary key,
    customer_id bigint not null,
    user_id bigint not null,
    reason varchar(255),
    source varchar(20) not null,
    created_at timestamp(6) with time zone not null,
    constraint uk_customer_blacklist_customer_id unique (customer_id),
    constraint fk_customer_blacklist_customer foreign key (customer_id) references customer (customer_id),
    constraint fk_customer_blacklist_user foreign key (user_id) references user_app (user_id)
);
create index idx_customer_blacklist_user_id on customer_blacklist (user_id);

-- Historial de inasistencias. Una cita se marca como no-show una sola vez (uk_customer_no_show_appointment_id).
-- cleared_at se rellena al sacar al cliente de la lista negra: el historial se conserva, pero el conteo
-- para el umbral de auto-bloqueo solo cuenta las filas con cleared_at IS NULL.
create table customer_no_show (
    customer_no_show_id bigint generated by default as identity primary key,
    customer_id bigint not null,
    appointment_id bigint not null,
    user_id bigint not null,
    created_at timestamp(6) with time zone not null,
    cleared_at timestamp(6) with time zone,
    constraint uk_customer_no_show_appointment_id unique (appointment_id),
    constraint fk_customer_no_show_customer foreign key (customer_id) references customer (customer_id),
    constraint fk_customer_no_show_appointment foreign key (appointment_id) references appointment (id),
    constraint fk_customer_no_show_user foreign key (user_id) references user_app (user_id)
);
create index idx_customer_no_show_customer_id on customer_no_show (customer_id);
