create table revoked_access_token (
    revoked_access_token_id bigint generated by default as identity,
    jti varchar(36) not null,
    expires_at timestamp(6) with time zone not null,
    revoked_at timestamp(6) with time zone not null,
    primary key (revoked_access_token_id)
);

alter table if exists revoked_access_token
    add constraint uk_revoked_access_token_jti unique (jti);
