create table account_blocked (
    account_blocked_od_id bigint generated by default as identity,
    user_id bigint not null,
    number_of_attempts smallint not null,
    expirated_at timestamp(6) with time zone,
    created_at timestamp(6) with time zone not null,
    primary key (account_blocked_od_id)
);

alter table if exists account_blocked
    add constraint fk_account_blocked_user foreign key (user_id) references user_app (user_id);
