-- Catalogo de precios de servicios (ej. "Corte basico"). user_id NULL = catalogo global
-- visible para todos los usuarios; con valor = servicio propio de ese usuario.
create table price_catalog (
    price_catalog_id integer generated by default as identity primary key,
    label varchar(255) not null,
    price bigint not null check (price > 0),
    user_id bigint,
    created_at timestamp(6) with time zone,
    constraint fk_price_catalog_user foreign key (user_id) references user_app
);
create index idx_price_catalog_user_id on price_catalog (user_id);
