spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: bookingapp
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      idle-timeout: 30000
      pool-name: bookingAppPoolConnection
      max-lifetime: 200000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false

  sql:
    init:
      mode: always
  ai:
    model:
      chat: deepseek
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        options:
          model: deepseek-flash
          temperature: 0.7
      


server:
  port: 8082


