spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: bookingapp
  datasource:
    url: ${DB_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      idle-timeout: 30000
      pool-name: bookingAppPoolConnection
      max-lifetime: 200000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: false

  sql:
    init:
      mode: always
  ai:
    model:
      chat: deepseek
    deepseek:
      api-key: ${DEEPSEEK_API_KEY}
      chat:
        options:
          model: deepseek-flash
          temperature: 0.7
      
security:
  jwt:
    private-key: ${JWT_PRIVATE_KEY_PATH:classpath:certs/private.pem}
    public-key: ${JWT_PUBLIC_KEY_PATH:classpath:certs/public.pem}
    expiration: 15
    refresh-expiration: 43200

  cookie:
    name: auth-token
    http-only: true
    secure: true
    max-age: 900
    same-site: Strict

cors:
  allowed-origins:
    - http://localhost:4200
  allowed-methods:
    - GET
    - POST
    - PUT
    - PATCH
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  exposed-headers:
    - Authorization
  allow-credentials: true
  max-age: 3600

server:
  port: 8082


